REM # HOMOLOGAÇÃO #
REM http://hom.nfe.fazenda.gov.br/PORTAL/WebServices.aspx
REM PADRAO  hom.nfe.SP.NfeRecepcao
REM PADRAO  nfe.SP.NfeRecepcao

wsdl	https://homnfe.sefaz.am.gov.br/services2/services/NfeRecepcao2
wsdl	https://homnfe.sefaz.am.gov.br/services2/services/NfeRetRecepcao2
wsdl	https://homnfe.sefaz.am.gov.br/services2/services/NfeCancelamento2
wsdl	https://homnfe.sefaz.am.gov.br/services2/services/NfeInutilizacao2
wsdl	https://homnfe.sefaz.am.gov.br/services2/services/NfeConsulta2
wsdl	https://homnfe.sefaz.am.gov.br/services2/services/NfeStatusServico2
wsdl	https://homnfe.sefaz.am.gov.br/services2/services/cadconsultacadastro2
wsdl	https://homnfe.sefaz.am.gov.br/services2/services/RecepcaoEvento
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeRecepcao2.asmx
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeRetRecepcao2.asmx
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeCancelamento2.asmx
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeInutilizacao2.asmx
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeConsulta2.asmx
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeStatusServico2.asmx
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx
wsdl	https://hnfe.sefaz.ba.gov.br/webservices/sre/RecepcaoEvento.asmx
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeRecepcao2
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeRetRecepcao2
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeCancelamento2
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeInutilizacao2
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeConsulta2
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeStatusServico2
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/CadConsultaCadastro2
wsdl	https://nfeh.sefaz.ce.gov.br/nfe2/services/RecepcaoEvento
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeRecepcao2?wsdl
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeRetRecepcao2?wsdl
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeCancelamento2?wsdl
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeInutilizacao2?wsdl
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeConsulta2?wsdl
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeStatusServico2?wsdl
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/CadConsultaCadastro2?wsdl
wsdl	https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeRecepcaoEvento?wsdl
wsdl	https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRecepcao2?wsdl
wsdl	https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetRecepcao2?wsdl
wsdl	https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeCancelamento2?wsdl
wsdl	https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl
wsdl	https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl
wsdl	https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl
wsdl	https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRecepcao2
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRetRecepcao2
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeCancelamento2
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeInutilizacao2
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeConsulta2
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeStatusServico2
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/CadConsultaCadastro2
wsdl	https://homologacao.nfe.ms.gov.br/homologacao/services2/RecepcaoEvento
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRecepcao2
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRetRecepcao2
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeCancelamento2
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeConsulta2
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeStatusServico2
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/cadconsultacadastro2
wsdl	https://hnfe.fazenda.mg.gov.br/nfe2/services/RecepcaoEvento
wsdl	https://homologacao.nfe2.fazenda.pr.gov.br/nfe/NFeRecepcao2?wsdl
wsdl	https://homologacao.nfe2.fazenda.pr.gov.br/nfe/NFeRetRecepcao2?wsdl
wsdl	https://homologacao.nfe2.fazenda.pr.gov.br/nfe/NFeCancelamento2?wsdl
wsdl	https://homologacao.nfe2.fazenda.pr.gov.br/nfe/NFeInutilizacao2?wsdl
wsdl	https://homologacao.nfe2.fazenda.pr.gov.br/nfe/NFeConsulta2?wsdl
wsdl	https://homologacao.nfe2.fazenda.pr.gov.br/nfe/NFeStatusServico2?wsdl
wsdl	https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeRecepcao2
wsdl	https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeRetRecepcao2
wsdl	https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeCancelamento2
wsdl	https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeInutilizacao2
wsdl	https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeConsulta2
wsdl	https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeStatusServico2
wsdl	https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/RecepcaoEvento
wsdl	https://webservice.set.rn.gov.br/projetonfehomolog/set_nfe/servicos/CadConsultaCadastroWS.asmx
wsdl	https://homologacao.nfe.sefaz.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx
wsdl	https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx
wsdl	https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx
wsdl	https://homologacao.nfe.sefaz.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx
wsdl	https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx
wsdl	https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx
wsdl	https://homologacao.nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRecepcao2.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRetRecepcao2.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeCancelamento2.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeInutilizacao2.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeConsulta2.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeStatusServico2.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/CadConsultaCadastro2.asmx
wsdl	https://homologacao.nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx
wsdl	https://hom.sefazvirtual.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx
wsdl	https://hom.sefazvirtual.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx
wsdl	https://hom.sefazvirtual.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx
wsdl	https://hom.sefazvirtual.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx
wsdl	https://hom.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx
wsdl	https://hom.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx
wsdl	https://hom.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx
wsdl	https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx
wsdl	https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx
wsdl	https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx
wsdl	https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx
wsdl	https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx
wsdl	https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx
wsdl	https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx
wsdl	https://hom.nfe.fazenda.gov.br/SCAN/NfeRecepcao2/NfeRecepcao2.asmx
wsdl	https://hom.nfe.fazenda.gov.br/SCAN/NfeRetRecepcao2/NfeRetRecepcao2.asmx
wsdl	https://hom.nfe.fazenda.gov.br/SCAN/NfeCancelamento2/NfeCancelamento2.asmx
wsdl	https://hom.nfe.fazenda.gov.br/SCAN/NfeInutilizacao2/NfeInutilizacao2.asmx
wsdl	https://hom.nfe.fazenda.gov.br/SCAN/NfeConsulta2/NfeConsulta2.asmx
wsdl	https://hom.nfe.fazenda.gov.br/SCAN/NfeStatusServico2/NfeStatusServico2.asmx

REM # PRODUCAO #
wsdl	https://nfe.sefaz.am.gov.br/services2/services/NfeRecepcao2
wsdl	https://nfe.sefaz.am.gov.br/services2/services/NfeRetRecepcao2
wsdl	https://nfe.sefaz.am.gov.br/services2/services/NfeCancelamento2
wsdl	https://nfe.sefaz.am.gov.br/services2/services/NfeInutilizacao2
wsdl	https://nfe.sefaz.am.gov.br/services2/services/NfeConsulta2
wsdl	https://nfe.sefaz.am.gov.br/services2/services/NfeStatusServico2
wsdl	https://nfe.sefaz.am.gov.br/services2/services/cadconsultacadastro2
wsdl	https://nfe.sefaz.am.gov.br/services2/services/RecepcaoEvento
wsdl	https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeRecepcao2.asmx
wsdl	https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeRetRecepcao2.asmx
wsdl	https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeCancelamento2.asmx
wsdl	https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeInutilizacao2.asmx
wsdl	https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeConsulta2.asmx
wsdl	https://nfe.sefaz.ba.gov.br/webservices/nfenw/NfeStatusServico2.asmx
wsdl	https://nfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx
wsdl	https://nfe.sefaz.ba.gov.br/webservices/sre/RecepcaoEvento.asmx
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/NfeRecepcao2
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/NfeRetRecepcao2
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/NfeCancelamento2
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/NfeInutilizacao2
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/NfeConsulta2
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/NfeStatusServico2
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/CadConsultaCadastro2
wsdl	https://nfe.sefaz.ce.gov.br/nfe2/services/RecepcaoEvento
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeRecepcao2?wsdl
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeRetRecepcao2?wsdl
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeCancelamento2?wsdl
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeInutilizacao2?wsdl
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeConsulta2?wsdl
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeStatusServico2?wsdl
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/CadConsultaCadastro2?wsdl
wsdl	https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeRecepcaoEvento?wsdl
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/NfeRecepcao2
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/NfeRetRecepcao2
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/NfeCancelamento2
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/NfeConsulta2
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/NfeStatus2
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/cadconsultacadastro2
wsdl	https://nfe.fazenda.mg.gov.br/nfe2/services/RecepcaoEvento
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/NfeRecepcao2
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/NfeRetRecepcao2
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/NfeCancelamento2
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/NfeInutilizacao2
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/NfeConsulta2
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/NfeStatusServico2
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/CadConsultaCadastro2
wsdl	https://nfe.fazenda.ms.gov.br/producao/services2/RecepcaoEvento
wsdl	https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRecepcao2?wsdl
wsdl	https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRetRecepcao2?wsdl
wsdl	https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeCancelamento2?wsdl
wsdl	https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl
wsdl	https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl
wsdl	https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl
wsdl	https://nfe.sefaz.mt.gov.br/nfews/CadConsultaCadastro
wsdl	https://nfe.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeRecepcao2
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeRetRecepcao2
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeCancelamento2
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeInutilizacao2
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeConsulta2
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeStatusServico2
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/CadConsultaCadastro2
wsdl	https://nfe.sefaz.pe.gov.br/nfe-service/services/RecepcaoEvento
wsdl	https://nfe2.fazenda.pr.gov.br/nfe/NFeRecepcao2?wsdl
wsdl	https://nfe2.fazenda.pr.gov.br/nfe/NFeRetRecepcao2?wsdl
wsdl	https://nfe2.fazenda.pr.gov.br/nfe/NFeCancelamento2?wsdl
wsdl	https://nfe2.fazenda.pr.gov.br/nfe/NFeInutilizacao2?wsdl
wsdl	https://nfe2.fazenda.pr.gov.br/nfe/NFeConsulta2?wsdl
wsdl	https://nfe2.fazenda.pr.gov.br/nfe/NFeStatusServico2?wsdl
wsdl	https://webservice.set.rn.gov.br/projetonfeprod/set_nfe/servicos/CadConsultaCadastroWS.asmx
wsdl	https://nfe.sefaz.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx
wsdl	https://nfe.sefaz.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx
wsdl	https://nfe.sefaz.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx
wsdl	https://nfe.sefaz.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx
wsdl	https://nfe.sefaz.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx
wsdl	https://nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx
wsdl	https://sef.sefaz.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx
wsdl	https://nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx
wsdl	https://nfe.fazenda.sp.gov.br/nfeweb/services/nferecepcao2.asmx
wsdl	https://nfe.fazenda.sp.gov.br/nfeweb/services/nferetrecepcao2.asmx
wsdl	https://nfe.fazenda.sp.gov.br/nfeweb/services/nfecancelamento2.asmx
wsdl	https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeinutilizacao2.asmx
wsdl	https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeconsulta2.asmx
wsdl	https://nfe.fazenda.sp.gov.br/nfeweb/services/nfestatusservico2.asmx
wsdl	https://nfe.fazenda.sp.gov.br/nfeweb/services/cadconsultacadastro2.asmx
wsdl	https://nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx
wsdl	https://www.sefazvirtual.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx
wsdl	https://www.sefazvirtual.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx
wsdl	https://www.sefazvirtual.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx
wsdl	https://www.sefazvirtual.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx
wsdl	https://www.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx
wsdl	https://www.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx
wsdl	https://www.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx
wsdl	https://nfe.sefazvirtual.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx
wsdl	https://nfe.sefazvirtual.rs.gov.br/ws/NfeRetRecepcao/NfeRetRecepcao2.asmx
wsdl	https://nfe.sefazvirtual.rs.gov.br/ws/NfeCancelamento/NfeCancelamento2.asmx
wsdl	https://nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx
wsdl	https://nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx
wsdl	https://nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx
wsdl	https://nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx
wsdl	https://www.scan.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx
wsdl	https://www.scan.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx
wsdl	https://www.scan.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx
wsdl	https://www.scan.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx
wsdl	https://www.scan.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx
wsdl	https://www.scan.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx
