//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.NFe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cms.NFe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] cancNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("cancNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] consCad_v2_00 {
            get {
                object obj = ResourceManager.GetObject("consCad_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] consReciNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("consReciNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] consSitNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("consSitNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] consStatServ_v2_00 {
            get {
                object obj = ResourceManager.GetObject("consStatServ_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] enviNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("enviNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] inutNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("inutNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] leiauteCancNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("leiauteCancNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] leiauteConsSitNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("leiauteConsSitNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] leiauteConsStatServ_v2_00 {
            get {
                object obj = ResourceManager.GetObject("leiauteConsStatServ_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] leiauteConsultaCadastro_v2_00 {
            get {
                object obj = ResourceManager.GetObject("leiauteConsultaCadastro_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] leiauteInutNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("leiauteInutNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] leiauteNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("leiauteNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] nfe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("nfe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] procCancNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("procCancNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] procInutNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("procInutNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] procNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("procNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] retCancNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("retCancNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] retConsCad_v2_00 {
            get {
                object obj = ResourceManager.GetObject("retConsCad_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] retConsReciNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("retConsReciNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] retConsSitNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("retConsSitNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] retConsStatServ_v2_00 {
            get {
                object obj = ResourceManager.GetObject("retConsStatServ_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] retEnviNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("retEnviNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] retInutNFe_v2_00 {
            get {
                object obj = ResourceManager.GetObject("retInutNFe_v2_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] schema_run {
            get {
                object obj = ResourceManager.GetObject("schema_run", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tiposBasico_v1_03 {
            get {
                object obj = ResourceManager.GetObject("tiposBasico_v1_03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xmldsig_core_schema_v1_01 {
            get {
                object obj = ResourceManager.GetObject("xmldsig_core_schema_v1_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
